name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy EMDR-AI to Cloudflare Pages
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Wrangler
        run: npm install -g wrangler@latest
      
      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          # Create or update the Pages project
          npx wrangler pages project create emdr-ai --production-branch main || true
          
          # Deploy the site
          npx wrangler pages deploy . --project-name emdr-ai --branch main
      
      - name: Get deployment URL
        run: |
          echo "🎉 Deployment complete!"
          echo "🌐 Your site should be available at: https://emdr-ai.pages.dev"
          echo "📝 Check the deployment status at: https://dash.cloudflare.com/?to=/:account/pages/view/emdr-ai"